name: Create Release

on:
  push:
    tags:
      - '0.*' # 匹配 0. 开头的标签

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    # Use Release environment for deployment protection
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

			- name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

			- name: Build and publish
        id: publish
        run: |
          pnpm release --publishOnly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
			
					- name: Create GitHub release
					id: release_tag
					uses: ChenXiaohui99
					env:
						GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
					with:
						tag_name: ${{ github.ref }}
						body: |
							Please refer to [CHANGELOG.md](https://github.com/ChenXiaohui99/vtj/blob/master/docs/CHANGELOG.md) for details.
